# dateset path
dataset_path: /home/sues/media/disk1/University-Release-MultiModel/University-Release
weight_save_path: /home/sues/save_model_weight

# apply LPN and set block number
LPN : 1
block : 2

# super parameters
batch_size : 16
num_epochs : 80
drop_rate : 0.35
weight_decay : 0.0001
lr : 0.01

#intial parameters
image_size: 384
fp16 : 1
classes : 701

model : MBF
query : drone
name: MBF

